<div class="row">
    <div class="span4">
        <h2>Hello there, I'm the GET Simulator.</h2>
        <p><?php echo $this->translate("Easy & Simple, using the GET simulator you can simulate advanced GET request with parameters configuration and headers configuration."); ?></p>
        <p><a class="btn btn-success" href="" target="_blank"><?php echo $this->translate("Simulate a request"); ?> &raquo;</a></p>
    </div>
</div>
