<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('Follow & Contribute'); ?></h2>
        <p><?php echo $this->translate("The eVias' dev-box is under active development and released under a GNU/GPL 3.0 Open Source license. Contributors are welcomed to this project. The idea is to retrieve all tools a developer may need in his daily work using Web protocols and implementing new web developments."); ?></p>
        <p><a class="btn btn-success" href="http://github.com/evias/dev-box" target="_blank"><?php echo $this->translate("eVias' dev-box on Github") ?> &raquo;</a></p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate("The toolbox for you") ?></h2>
        <p><?php echo $this->translate("Simply go to the 'Modules' section and navigate through the web development utilities. Some of the features may use an iframe to provide full technology capabilities."); ?></p>
        <p><a class="btn btn-success" href="<?php echo "http://" . $_SERVER["HTTP_HOST"] . "/box/home/dashboard"; ?>" target="_blank"><?php echo $this->translate('Explore the Toolbox dashboard') ?> &raquo;</a></p>
   </div>
</div>
